name: CI POC-DigitClassifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Unit Tests
        run: ./gradlew test jacocoUnitTestReport

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup ANDROID_HOME
        run: echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > ./local.properties

      - name: Install Android Command Line Tools
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
          unzip -q commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          echo "y" | sdkmanager --licenses
          echo "y" | sdkmanager --install "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          ls -l $ANDROID_HOME/cmdline-tools/latest/bin
        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Run Sanity build
        run: ./gradlew assemble
        env:
          ANDROID_HOME: ${{ secrets.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ secrets.ANDROID_SDK_ROOT }}
